### ISSUE TITLE
Change encoding for CP866

### ISSUE THREAD

**Issue by paryz1i12** [anklav24/123#1]
Hi! For russian characters you would want to use the CP866 encoding, that may actually help with your case. CP866 is compatible with Unicode, UTF-32 and UTF-16, it should help you with saving the text. I’m not sure though, so check if it works :)

**Comment by anklav24** [comment]
Thanks, but it doesn't works.
https://github.com/anklav24/123/blob/master/Create-New-GitHub-Repositories-From-API.bat
